### ISSUE TITLE
update to version v2.17.1 (2023/06/13)

### ISSUE THREAD

**Issue by naz9ul** [awesometic/realtek-r8152-dkms#10]
Hi tanks for the very good work !

Is it possible to have a news build with version v2.17.1 (2023/06/13).

Or if not, what are the step to do it with you actuel git ?

Best regards,

Sylvain

**Comment by awesometic** [comment]
Hello, thank you for notifying the new version :)

I updated and pushed the changes to the repository.

When you want to make a patch for the new version, you should check the applied patches to the source codes so far.

This time, the new version 2.17.1 contains the contents of the patches I made for this repository, which are supporting the new Linux kernel versions 5.18/6.1 or above. So I didn't apply them again.

And then after a simple build test using Makefile, you can make a commit and PR. The commit message would be perfect if you follow the format of this repository.
