### ISSUE TITLE
Cannot build module

### ISSUE THREAD

**Issue by TheOzzOne** [awesometic/realtek-r8152-dkms#11]
Board is a Raspberry Pi 4, running 64bit Debian 11 Bullseye, kernel is 6.1.21-v8+, headers installed via raspberrypi-kernel-headers and are appropriate version 6.1.21-v8+.

Print of uname -a
Linux orthanc 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

Device info: 
ASUS 10/100/1000/2500 USB-C2500
Link to tech specs: http://en.techinfodepot.shoutwiki.com/wiki/ASUS_USB-C2500
[Realtek](http://en.techinfodepot.shoutwiki.com/wiki/Realtek) RTL8156B • USB ID: [0b05:1976]
Interesting to note, it uses a different Vendor ID and Product IDs from all other devices mentioned in 50-usb-realtek-net.rules; however it is mentioned in all of the tested repo's r8152.c files.

Doesn't seem to matter which method I use to try and build the module, I error out. See prints below. 

Troubleshooting steps taken: 
Fresh 32-bit install (same problem)
Fresh 64-bit install (same problem)
Attempted build on Rock5b (Just to make sure I'm not crazy), 5.10 kernel (make successful)

Attempted building from the following sources: 
[Realtek provided download](https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-usb-3-0-software)
[wget's repo](https://github.com/wget/realtek-r8152-linux)
[menzo2003's repo](https://github.com/menzo2003/r8152-driver)
[This repo](https://github.com/awesometic/realtek-r8152-dkms)

Is there something fundamentally incompatible with this kernel version? I see there are a number of people who have it working on various other kernel versions; including yourself fixing it on [6.1 for Proxmox](https://github.com/awesometic/realtek-r8125-dkms/issues/31).

Possibly something silly with the aarch64 architecture instead of x86? 

Thank you so much for your help!

------------------------------------------------------------------------------------------------------

Print from autorun.sh:
```
ERROR: modpost: /home/pi/Downloads/realtek-r8152-dkms-master/src/r8152: 'rtl8152_get_version' exported twice. Previous export was in vmlinux
make[3]: *** [scripts/Makefile.modpost:126: /home/pi/Downloads/realtek-r8152-dkms-master/src/Module.symvers] Error 1
make[2]: *** [Makefile:1964: modpost] Error 2
make[1]: *** [Makefile:24: modules] Error 2
make: *** [Makefile:18: modules] Error 2
```

Print from ./dkms-install
```
About to run dkms install steps...

Creating symlink /var/lib/dkms/r8152/2.17.1/source ->
                 /usr/src/r8152-2.17.1

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=6.1.21-v8+ -C /lib/modules/6.1.21-v8+/build M=/var/lib/dkms/r8152/2.17.1/build.........(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.1.21-v8+ (aarch64)
Consult /var/lib/dkms/r8152/2.17.1/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=6.1.21-v8+ -C /lib/modules/6.1.21-v8+/build M=/var/lib/dkms/r8152/2.17.1/build.........(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.1.21-v8+ (aarch64)
Consult /var/lib/dkms/r8152/2.17.1/build/make.log for more information.
Finished running dkms install steps.
Copy the dedicated udev rules file...
Restarting udev...
Finished.
```

Print from .deb dpkg install: 
```
sudo dpkg -i realtek-r8152-dkms_2.17.1-1_arm64.deb 
Selecting previously unselected package realtek-r8152-dkms.
(Reading database ... 124154 files and directories currently installed.)
Preparing to unpack realtek-r8152-dkms_2.17.1-1_arm64.deb ...
Unpacking realtek-r8152-dkms (2.17.1-1) ...
Setting up realtek-r8152-dkms (2.17.1-1) ...
Loading new realtek-r8152-2.17.1 DKMS files...
It is likely that 6.1.21-v8+ belongs to a chroot's host
Building for 6.1.21-v8+
Building for architecture arm64
Building initial module for 6.1.21-v8+
Error! Bad return status for module build on kernel: 6.1.21-v8+ (arm64)
Consult /var/lib/dkms/realtek-r8152/2.17.1/build/make.log for more information.
dpkg: error processing package realtek-r8152-dkms (--install):
 installed realtek-r8152-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 realtek-r8152-dkms
```

Output from make.log: 
```
DKMS make.log for realtek-r8152-2.17.1 for kernel 6.1.21-v8+ (arm64)
Wed 23 Aug 13:20:33 MST 2023
make -C src/ modules
make[1]: Entering directory '/var/lib/dkms/realtek-r8152/2.17.1/build/src'
make -C /lib/modules/6.1.21-v8+/build M=/var/lib/dkms/realtek-r8152/2.17.1/build/src modules
make[2]: Entering directory '/usr/src/linux-headers-6.1.21-v8+'
  CC [M]  /var/lib/dkms/realtek-r8152/2.17.1/build/src/r8152.o
  MODPOST /var/lib/dkms/realtek-r8152/2.17.1/build/src/Module.symvers
ERROR: modpost: /var/lib/dkms/realtek-r8152/2.17.1/build/src/r8152: 'rtl8152_get_version' exported twice. Previous export was in vmlinux
make[3]: *** [scripts/Makefile.modpost:126: /var/lib/dkms/realtek-r8152/2.17.1/build/src/Module.symvers] Error 1
make[2]: *** [Makefile:1964: modpost] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-6.1.21-v8+'
make[1]: *** [Makefile:24: modules] Error 2
make[1]: Leaving directory '/var/lib/dkms/realtek-r8152/2.17.1/build/src'
make: *** [Makefile:18: modules] Error 2
```

**Comment by awesometic** [comment]
Hello,

I think this line represents the culprit

```
ERROR: modpost: /var/lib/dkms/realtek-r8152/2.17.1/build/src/r8152: 'rtl8152_get_version' exported twice. Previous export was in vmlinux
```

I'm not sure, but it seems like your kernel image has the same symbol named `rtl8152_get_version` so the compiler argues about this point there is the same symbol already exported.

So for a workaround, you can comment out the following line and try it again.
- https://github.com/awesometic/realtek-r8152-dkms/blob/master/src/r8152.c#L20219

If it doesn't work, you can ask this to the Raspberry Pi forum since this is related to the prebuilt kernel image.

Maybe the Raspberry Pi kernel has the vendor network module already, which uses the `r8152.c` file that has the same history as this repository.

**Comment by TheOzzOne** [comment]
Thank you so much for the prompt and helpful answer, awesometic! That worked! 

I was able to comment out the the line 20219: 
`//EXPORT_SYMBOL_GPL(rtl8152_get_version);`

Output from sudo ./autorun.sh is now: 
`Build the module and install
Warning: modules_install: missing 'System.map' file. Skipping depmod.
DEPMOD 6.1.21-v8+
load module r8152
Updating initramfs. Please wait.
update-initramfs: Generating /boot/initrd.img-6.1.21-v8+
Completed.`

It looks like you are correct - according to this thread - https://forums.raspberrypi.com/viewtopic.php?t=294150 : 

> "you could not compile the vendor r8152 module for a kernel that already has mainline r8152 driver built in"

It appears that the RPI4 kernel has had the r8152 module built in; I would need to rebuild kernel without the r8152 driver in order to compile & add this one. 

My problem now is getting <any> r8152 module to load for the ASUS USB-C2500 I'm using, as it appears to insist on loading the cdc_ncm driver @ half duplex instead of full duplex.

**Comment by Edwin-Dijk** [comment]
@TheOzzOne If you ever found out how to get the USB-C2500 to work on the Pi please contact me. I have gotten to your last comment's step exactly but no further luck unfortunately.

**Comment by TheOzzOne** [comment]
As a final note to this; as of kernel 6.1.0-rpi8-rpi-v8, I am now connected at 2.5gbE through the ASUS USB-C2500 adapter. 

Reported through ethtool.
![image](https://github.com/awesometic/realtek-r8152-dkms/assets/15208183/1359bd66-9291-42b7-83c1-937bd3fb8490)

Tested with iperf 3. 
![image](https://github.com/awesometic/realtek-r8152-dkms/assets/15208183/cf852a00-47b8-4daa-a9dd-1d911606aa12)
Not full speed, but i'm also not using Jumbo Frames or any kind of network optimization.

**Comment by Edwin-Dijk** [comment]
@TheOzzOne Oh that's cool! Couldnt find anything in the linux driver release notes about this quickly, am curious when they added the official support, either way, I'm happy that it's now native :)
