### ISSUE TITLE
Kernel 6.4 error

### ISSUE THREAD

**Issue by adi1** [awesometic/realtek-r8152-dkms#12]
Building dkms module on kernel 6.4 gives the following error:

```
/var/lib/dkms/r8152/2.17.1/build/src/r8152.c:2094:10: error: implicit declaration of function ‘skb_gso_segment’; did you mean ‘skb_gso_reset’? [-Werror=implicit-function-declaration]
 2094 |   segs = skb_gso_segment(skb, features);
      |          ^~~~~~~~~~~~~~~
      |          skb_gso_reset
```

I was able to work around this by adding the following to `r8152.c`, taken from `https://github.com/wget/realtek-r8152-linux/blob/master/r8152.c`:

```c
// Linux 6.4.10 added net/gso.h
#if defined __has_include
#if __has_include (<net/gso.h>)
#include <net/gso.h>
#endif
#endif
```

**Comment by awesometic** [comment]
Thank you for the report and for suggesting a solution. @corytodd made a PR and it is just merged so that this issue now is gone :)
