### ISSUE TITLE
error - package architecture (amd64) does not match system (arm64)

### ISSUE THREAD

**Issue by roblatour** [awesometic/realtek-r8152-dkms#23]
after:.
wget https://github.com/awesometic/realtek-r8152-dkms/releases/download/2.17.1-3/realtek-r8152-dkms_2.17.1-3_amd64.deb
(which worked fine)

I ran the command:
sudo dpkg -i realtek-r8152-dkms*.deb

but got this error:

dpkg: error processing archive realtek-r8152-dkms_2.17.1-3_amd64.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 realtek-r8152-dkms_2.17.1-3_amd64.deb

Running this on a Raspberry Pi 5 running Ubuntu 24.04 Lite.

**Comment by awesometic** [comment]
Hi, sorry for the too-late reply.

Right, you may know the solution. To run this on ARM64 machine, you should build this on the same architecture machine. Then the package will be generated for ARM64. This will work.

**Comment by roblatour** [comment]
The Raspberry Pi 5 uses a 64-bit 2.4 GHz quad-core ARM Cortex-A76 processor.

Regardless, I personally no longer need this as I switched to Armbian and device I was using worked with it.

**Comment by awesometic** [comment]
Armbian supports various peripherals out of the box. I'm glad that you have solved it :)
