### ISSUE TITLE
Upgrade (version?) etc.

### ISSUE THREAD

**Issue by piknew** [awesometic/realtek-r8152-dkms#3]
I will start with work "unfortunately". I had a case that dkms and package was installed (I belive in newest version). Then I have performed some of upgrade for apt packages (apt upgrade). And unfortunately I haven't catched error which was triggered by this process (error was definitely related to dkms).

I was looking at files and noticed strange (or maybe this is normal?) thing. This is for your evaluation (remark - this file is in 2.16.3-2 package):

![obraz](https://user-images.githubusercontent.com/39850926/195530312-d04c2c75-7c2d-4acb-a816-5559df80a79c.png)

**Comment by awesometic** [comment]
Oh I didn't notice that. Thank you for letting me know!

I will update my package and post the results here.

**Comment by awesometic** [comment]
The issue has been fixed. Thanks again 😃 
Closed this issue.
