### ISSUE TITLE
Compatibility with armhf

### ISSUE THREAD

**Issue by piknew** [awesometic/realtek-r8152-dkms#4]
I have a few boards with armhf architecture. I have tried to compile the driver and it seems that it is working. However, I didn't tested driver itself. Is it possible to somehow remove restriction for architecture? Of course - release shall be given if also driver is verified.

![screenshot 241](https://user-images.githubusercontent.com/39850926/195540552-9f2b81fe-b0ec-43fe-a102-5644b6300816.png)

**Comment by awesometic** [comment]
I believe there is no way to test the driver for a specific architecture on the other machine that uses another architecture.

I think you can try with the USB ethernet module that you're using for the x86_64 machine. 🤔

**Comment by piknew** [comment]
Exactly. I will test it and I will let you know (I have two other USB3 rtl8156 adapters). So, I will build driver for armhf platform and then I will let you know the results. BTW. Is it some kind of parameter for "deb" archive?

**Comment by piknew** [comment]
By parameter I mean architecture, for which deb package is targeted for. Please note that for example a few versions ago - there was deb package provided for arm64.

Obvious problem with deb is that it cannot be installed (because of architecture mismatch). As this is just source code and if it can be compiled and used (this will be tested by me) - there is no reason to define only amd64.

![obraz](https://user-images.githubusercontent.com/39850926/195573173-56118d07-d39d-498b-a3cf-16fc9721fbc7.png)

**Comment by piknew** [comment]
I have compiled driver. It is working without any issues on armhf (similarly to amd64). I have only USB2 on my arm SBC so, the speed is somehow limited.

A few lines from dmesg:

![image](https://user-images.githubusercontent.com/39850926/195701375-3edf97a9-7f2b-491a-93ed-4355873b2f27.png)

**Comment by awesometic** [comment]
Thanks for confirming it's working. I can prepare other deb packages for arm and arm64 architectures.
I will try, and let you know the results.

**Comment by awesometic** [comment]
I forgot, I already have set building amd64 as well as arm, arm64 architectures in my Launchpad.

![스크린샷 2022-10-14 오전 11 22 45](https://user-images.githubusercontent.com/10906167/195747420-2db3adf6-1949-41c5-bb28-1e6b39fee61d.png)

Can you use it after adding this Launchpad repository?

```
sudo add-apt-repository ppa:awesometic/ppa
```

**Comment by piknew** [comment]
Sorry for long time of no answer. I have downloaded package for armhf and... it is working (I have added dkms on Ornage Pi, with r8156b USB adapter; speed of course was limited because of USB2.0).

So, this issue can be closed. Thank you.
