### ISSUE TITLE
Exec Format Error while running 'modprobe r8152' in Linux 6.2.8, Ubuntu 22.10

### ISSUE THREAD

**Issue by perryvaldez** [awesometic/realtek-r8152-dkms#9]
I've installed the Realtek 8152 driver via PPA. However, my TP-Link UE300C USB-Ethernet dongle remains undetected.

Step I did after setting up repo access to `ppa:awesometic/ppa`:

```
# uname -r
6.2.8-060208-generic

# cat /etc/issue
Ubuntu 22.10 \n \l

# apt install realtek-r8152-dkms
...
# depmod -a
# update-initramfs -u
...

# modprobe r8152
modprobe: ERROR: could not insert 'r8152': Exec format error

# dmesg | tail
...
[ 5567.266290] module: x86/modules: Skipping invalid relocation target, existing value is nonzero for type 1, loc 00000000b244c428, val ffffffffc1e9a8b0

```
Any ideas?

**Comment by perryvaldez** [comment]
A bit more details:

```
# cat /proc/version
Linux version 6.2.8-060208-generic (kernel@sita) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.2.0-9ubuntu1) 12.2.0, GNU ld (GNU Binutils for Ubuntu) 2.39) #202303220943 SMP PREEMPT_DYNAMIC Wed Mar 22 13:50:04 UTC 2023

# gcc --version
gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0
...

```

**Comment by awesometic** [comment]
Hello,

Sorry for the really late reply. Seems like that is due to the invalid architecture of the installed binary but I can't specify that.

Instead of the PPA way, you can try to build it yourself from the source codes. If it also spits out that error, we should find out why it happens 🤔

**Comment by awesometic** [comment]
This link may help you: https://beebom.com/how-fix-exec-user-process-caused-exec-format-error-linux/

**Comment by awesometic** [comment]
Since this issue has not active last 2 months, I will close this issue
